Fix PeekAsync for ServiceBusScaleMonitor
Azure/azure-functions-servicebus-extension pull request #121
Opened 2020-11-09 21:11 UTC by wenhzha

```message = await _receiver.Value.PeekAsync()``` intends to peek the first message . However, in this usage, the client remembera the sequence number of the last message and peeks the next message on the next call. For example, if there are two messages in the queue, calling peekAsync returns the first message. If you call peekAsync again, it returns the second message. If you call peekAsync again, it will return no message or null. 

Use PeekBySequenceNumberAsync instead so it forces the client to check the first message from sequence number =0.

2020-11-09 22:27 UTC, gzuber approved these changes

2020-11-10 18:54 UTC, sidkri requested changes
Checking to see how this was verified.  Sequence numbers embed partition information and are increasing within a partition.  I could not find special treatment for a zero sequence number in the ServiceBus source code.

2020-11-10 23:06 UTC, sidkri approved these changes
Discussed offline to understand how this change was validated. @wenhzha please update the PR with details of how you validated the change since we don't have existing integration test coverage for the scale monitor logic.

2020-11-10 23:14 UTC, alrod approved these changes

2020-11-10 23:18 UTC, merged

2020-11-11 17:32 UTC, mathewc commented
Thanks for the investigation and fix @wenhzha!